### ISSUE TITLE
Hi, PengChen

### ISSUE THREAD

**Issue by makerthink** [PuddingPengChen/Magic3D#1]
It's great to see such a project.
I am looking for a 3D slicer expert like u.
If u are interested in my project, please contact me: Q:1841435.

**Comment by PuddingPengChen** [comment]
Hi,I am so glad you are interest in my project. Your project is the one I wanted to do before,so I am very interest in it. I have  add your Q ，wait your reply.

**Comment by ForeverDavid** [comment]
Dear Chen,
Thanks for your sharing, this project is compiled with VS under windows? Can you tell me how to run this project, I wanna use it to finish my DIY DLP 3D Printer. My QQ is 947705813. Waiting for your reply.

**Comment by youdemo** [comment]
Dear Chen,
Thanks for your sharing, this project was compiled under windows have some problems,can you help me?My Q is:3077098040  waiting for your reply.

**Comment by twosilly** [comment]
话说我感觉大哥貌似是个中国人！咋可以说中文不？？原谅我英语太烂！
大哥这项目是在啥到底是在qt几上运行的啊？？有没有qt5版本的？？我用qt4.8.2编译不通过！（当然也可能是我的qt没编译对！）拜托了大哥！QQ：1096950444,麻烦你了！

**Comment by SHINOTECH** [comment]
微信：diaman

**Comment by SHINOTECH** [comment]
微信：diaman

**Comment by SHINOTECH** [comment]
微信：diaman

**Comment by PriscyllaT** [comment]
Dear Chen,
Thanks for your sharing your project. I would like help in how to compile and run this project under windows. Can you help? How is Qt required?

Thanks,
